server:
  port: 8003
  servlet:
    contextPath: "/api/law-service/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: law-service
  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: S10P22A604
      password: qlpoh4yX1A
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P22A604?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8

  # elasticsearch
  elasticsearch:
    host: j10a604.p.ssafy.io
    port: 19201
    indices:
      statutesIndexName: statute_index
      statutetexsIndexName: statutetext_index
      precidentsIndexName: precident_index
      termsIndexName: term_index

  # jpa
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show-sql: true
        format_sql: true
#      open-in-view: false

#logging
logging:
  level:
    com.sobolaw.aop: TRACE
    org:
      hibernate.orm.jdbc.bind: trace
      springframework:
        web: DEBUG


eureka:
  client:
    # disable eureka discovery client
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}