version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    restart : unless-stopped
    ports:
      - "6379:6379"

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    image: elasticsearch_nori
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - /home/ubuntu/esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  frontend:
    container_name: frontend
    image: frontend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    user: root

  eureka_server:
    container_name: eureka_server
    image: eureka_server
    ports:
      - "8761:8761"

  api_gateway:
    container_name: api_gateway
    image: api_gateway
    depends_on:
      - eureka_server
    ports:
      - "8000:8000"

  user_service:
    container_name: user_service
    image: user_service
    depends_on:
      - api_gateway
      - redis
    ports:
      - "8001:8001"
  
  ai_service:
    container_name: ai_service
    image: ai_service
    depends_on:
      - api_gateway
    ports:
      - "8002:8002"

  law_service:
    container_name: law_service
    image: law_service
    depends_on:
      - api_gateway
      - elasticsearch
    ports:
      - "8003:8003"
  
  recommend_service:
    container_name: recommend_service
    image: recommend_service
    depends_on:
      - api_gateway
    ports:
      - "8004:8004"

