server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # euraka registry
    fetch-registry: false         # registy
  server:
    waitTimeInMsWhenSyncEmpty: 1000
