server:
  port: 8001
  servlet:
    contextPath: "/api/user-service/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: user-service
  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: S10P22A604
      password: qlpoh4yX1A
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P22A604?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8

# social security
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 클라이언트아이디
            client-secret: 시크릿키
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname
          naver:
            client-id: 클라이언트아이디
            client-secret: 시크릿키
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  # jpa
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
#        show-sql: true
        format_sql: true
#      open-in-view: false

#logging
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: trace
    root: INFO
    org:
      springframework:
        web: INFO
        apache:
          tiles: DEBUG
        springframework:
          boot: DEBUG

eureka:
  client:
    # disable eureka discovery client
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# jwt
jwt:
  secret-key: "나만의 시크릿 키값"
  expiration: "604800000" # 7일

