server:
  port: 8001
  servlet:
    contextPath: "/api/user-service/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: user-service
  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: S10P22A604
      password: qlpoh4yX1A
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P22A604?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8

  # jpa
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
#        show-sql: true
        format_sql: true
#      open-in-view: false

#logging
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: trace
    root: INFO
    org:
      springframework:
        web: INFO
        apache:
          tiles: DEBUG
        springframework:
          boot: DEBUG

eureka:
  client:
    # disable eureka discovery client
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

openai:
  api-key: "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"
  base-url: "https://api.openai.com/v1/engines/gpt-3.5-turbo-0125/completions"
#  https://api.openai.com/v1/chat/completions
  model: "gpt-3.5-turbo-0125"
  url:
    prompt=https://api:
      openai:
        com/v1/chat/completions: