server:
  port: 8005
  servlet:
    contextPath: "/api/notification-service/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: notification-service
  devtools:
    livereload:
      enabled: true
  data:
    redis:
      host: redis
      port: 6379

#logging
logging:
  level:
    org:
      springframework.web: INFO
      hibernate.orm.jdbc.bind: TRACE
    com.sobolaw.aop: TRACE

eureka:
  client:
    #     disable eureka discovery client
    #    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
