server:
  port: 8000
  servlet:
    contextPath: "/api/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          predicates:
            - Path=/api/user-service/**
          uri: lb://USER-SERVICE

        - id: ai-service
          predicates:
            - Path=/api/ai-service/**
          uri: lb://AI-SERVICE

        - id: law-service
          predicates:
            - Path=/api/law-service/**
          uri: lb://LAW-SERVICE

        - id: recommend-service
          predicates:
            - Path=/api/recommend-service/**
          uri: lb://RECOMMEND-SERVICE

        - id: notification-service
          predicates:
            - Path=/api/notification-service/**
          uri: lb://NOTIFICATION-SERVICE

        - id: board-service
          predicates:
            - Path=/api/board-service/**
          uri: lb://BOARD-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka
