version: "3"
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/esdata1:/home/ubuntu/esdata1
    user: root
