server:
  port: 8006
  servlet:
    contextPath: "/api/board-service/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: board-service

  devtools:
    livereload:
      enabled: true

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: S10P22A604
      password: qlpoh4yX1A
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P22A604?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        #        default_batch_fetch_size: 1000
        #        show-sql: true
        format_sql: true
#      open-in-view: false

#logging
logging:
  level:
    org:
      springframework.web: INFO
      hibernate.orm.jdbc.bind: TRACE
    com.sobolaw.aop: TRACE

eureka:
  client:
    #     disable eureka discovery client
    #    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
